app:
  server:
    port: 7006
  grpc:
    port: 7060
  database:
    host: localhost
    port: 5432
    name: SweWorkflow
    schema: sweworkflow
    username: postgres
    password: 123456
  kafka:
    host: localhost
    port: 9092
  config:
    timezone: Asia/Ho_Chi_Minh